// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nqyzaxzlwbxkdjylmueu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5xeXpheHpsd2J4a2RqeWxtdWV1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwNDE3NjIsImV4cCI6MjA3MzYxNzc2Mn0.6CxEDOf5ADc3NjupRAmkCn8ARxUkLDWjs163p-ndIBQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});